spring.application.name=canvas-service
server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5432/leetdoodle
spring.datasource.username=leetdoodle
spring.datasource.password=leetdoodle

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=canvas
spring.flyway.default-schema=canvas

grpc.server.port=9091
