spring.application.name=submissions-service
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/leetdoodle
spring.datasource.username=leetdoodle
spring.datasource.password=leetdoodle

# Tell Flyway to create/migrate only the submissions schema
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=submissions
spring.flyway.default-schema=submissions

# RabbitMQ connection
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=leetdoodle
spring.rabbitmq.password=leetdoodle
